### PR TITLE
these addLayer calls do not spark joy

### PR DESCRIPTION
**Pull request by jmcbroom**

### CODE REVIEW

**Comment by mikefresh** [comment]
neat!
Alt Text

**Comment by mikefresh** [comment]
Why add the mapstyle locally instead of from mapbox on load?

**Comment by jmcbroom** [comment]
basically, it's easier to make edits/add layers if it's right there in the repository instead of making edits in the Mapbox interface.

**Comment by mikefresh** [comment]
I assume it pulls it all in from mb either way so it's not adding any size issues i assume. But it does mean that if GIS makes changes to the basemaps or someone else asks them to make an update on their behalf for the app, then we have to be in the loop and do a new release. 

But either way I don't think that's a problem we need to address right now so this is groovy.

**Comment by jmcbroom** [comment]
Cool. We can always upload this `mapStyle.json` & go back to loading from Mapbox once we've finalized the style/finished development

**Pull request merged**
